import './globals.css'
import "../fonts/line-awesome-1.3.0/css/line-awesome.css";
// import "../styles/index.scss";
// import "rc-slider/assets/index.css";
import { Inter } from 'next/font/google'
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import ScrollToTopButton from './components/ScrollToTopButton';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header className={"shadow-sm dark:border-b dark:border-neutral-700 m-auto"} />
        {children}
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  )
}
